#!/bin/bash

# MASTER SETUP SCRIPT for Trading Bots
# Installs systemd services AND cron jobs for both equity and options bots
# Also sets up webhook router

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  MASTER SETUP - Trading Bots + Webhook Router                  ║"
echo "║  Systemd Services + Cron Jobs Configuration                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "❌ This script must be run as root (use: sudo bash $0)"
   exit 1
fi

echo "=========================================="
echo "Step 1: Setup Systemd Services"
echo "=========================================="
echo ""

bash /root/santhosh/trading/setup_systemd.sh

echo ""
echo "=========================================="
echo "Step 2: Setup Equity Bot Cron Jobs"
echo "=========================================="
echo ""

bash /root/santhosh/trading/equity/setup_cron.sh

echo ""
echo "=========================================="
echo "Step 3: Setup Options Bot Cron Jobs"
echo "=========================================="
echo ""

bash /root/santhosh/trading/options/setup_cron.sh

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  SETUP COMPLETE                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📌 CONFIGURATION SUMMARY"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "PORT CONFIGURATION:"
echo "  🌐 Port 80   : Webhook Router (receives TradingView alerts)"
echo "  📈 Port 8080 : Equity Bot (processes shares/derivatives)"
echo "  📊 Port 8081 : Options Bot (processes CE/PE)"
echo ""
echo "DAILY SCHEDULE (Mon-Fri):"
echo "  🔄 08:45 AM  : System reboot (5-min delay)"
echo "  🚀 08:55 AM  : Webhook router starts (listens for alerts)"
echo "  🕘 09:00 AM  : Options bot auto-starts"
echo "  🕘 09:05 AM  : Equity bot auto-starts"
echo "  🔍 Every 30m : Health checks (both bots)"
echo "  📊 16:00 PM  : Options bot EOD export"
echo "  🧹 16:30 PM  : Equity bot cleanup"
echo "  🗑️  00:00 AM : Log cleanup (Sundays)"
echo ""
echo "SERVICES ENABLED (systemd):"
echo "  ✅ webhook-router (auto-restart on failure)"
echo "  ✅ equity-trading-bot (auto-restart on failure)"
echo "  ✅ options-trading-bot (auto-restart on failure)"
echo ""
echo "ALERT FLOW:"
echo "  TradingView → Port 80 (Router) → Port 8080 (Equity) + Port 8081 (Options)"
echo ""
echo "TRADINGVIEW CONFIGURATION:"
echo "  Configure your TradingView webhook to:"
echo "  http://your-server-ip/webhook"
echo ""
echo "  Same webhook for BOTH bots - router handles distribution!"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 USEFUL COMMANDS"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Check Cron Jobs:"
echo "  crontab -l"
echo ""
echo "Check Service Status:"
echo "  sudo systemctl status webhook-router"
echo "  sudo systemctl status equity-trading-bot"
echo "  sudo systemctl status options-trading-bot"
echo ""
echo "Start Services (manual):"
echo "  sudo systemctl start webhook-router"
echo "  sudo systemctl start equity-trading-bot"
echo "  sudo systemctl start options-trading-bot"
echo ""
echo "View Logs (live):"
echo "  sudo journalctl -u webhook-router -f"
echo "  sudo journalctl -u equity-trading-bot -f"
echo "  sudo journalctl -u options-trading-bot -f"
echo ""
echo "Check Router Health:"
echo "  curl http://127.0.0.1/health"
echo "  curl http://127.0.0.1/stats"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "🎯 NEXT STEPS"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "1. ✅ Services installed and enabled for auto-start"
echo "2. ✅ Cron jobs configured for daily automation"
echo "3. 📝 Update TradingView webhook URL to: http://your-server-ip/webhook"
echo "4. 🧪 Test router at 8:55 AM tomorrow or manually start:"
echo "     sudo systemctl start webhook-router"
echo "5. ✅ Both bots will automatically receive alerts from TradingView"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo ""

